name: fcharts_example
description: Demonstrates how to use the fcharts plugin.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  fcharts:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true