name: fcharts
description: >
  A chart library for Flutter. Create beautiful,
  animated, responsive charts using a simple and intuitive API.
version: 0.0.11
author: Keenan Thompson <keenan@keenant.com>
homepage: https://github.com/thekeenant/fcharts

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.1.2"
  collection: "^1.14.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
